### ISSUE TITLE
Unable to scroll window with mouseWheel property disabled

### ISSUE THREAD

**Issue by skodko** [micheleriva/vue-product-spinner#27]
I'm not able to scroll window, when cursor is over component with mouseWheel property set to false. It's bit a problem when component is relatively high and stretch to full screen. 
I looked trough the source code, found out this issue can be hot fixed by changing component method `handleWheel`.

Original method:
```
handleWheel: function handleWheel(event) {
      event.preventDefault();
      if (this.mouseWheel) {
        this.handleMovement(event.deltaY);
      }
}
```

Hot fixed:
```
handleWheel: function handleWheel(event) {
      if (this.mouseWheel) {
        event.preventDefault();
        this.handleMovement(event.deltaY);
      }
}
```

**Comment by micheleriva** [comment]
Thanks a lot @skodko !
Will release today an hotfix.
