### ISSUE TITLE
render images (quasar framework) 

### ISSUE THREAD

**Issue by vzx7** [micheleriva/vue-product-spinner#28]
I use quasar framework. I have problem with render my images.

/src/assets/images/models/kia/ - this is images direcotry.

And my code
`images = [...Array(62)].map(
  (_, i) =>
    `~assets/images/models/kia/img_${i + 1}.png`
)`

And I ... 404.
I tryed more different variant, always not found.
What is not correct?
![1577038599594](https://user-images.githubusercontent.com/21075456/71325618-70263000-2500-11ea-9c42-d07976d17e69.jpg)

**Comment by micheleriva** [comment]
Hi @vzx7 ,
it seems that the problem is with the image path, as you can see you're trying to fetch them from the `~assets` folder. Maybe the correct path is `/assets` (without `~`?)
