### ISSUE TITLE
Fix images prefetch

### ISSUE THREAD

**Issue by micheleriva** [micheleriva/vue-product-spinner#4]
**Describe the bug**
After images prefetch, `imagesAreReady` doesn't set to `true`

**To Reproduce**
1. Go to 'https://micheleriva.github.io/vue-product-spinner/
2. Click on a car brand
3. Images doesn't load

**Expected behavior**
Images should be loaded pretty quickly

**Comment by eLeontev** [comment]
I'll try take care. looks like you forgot to add `this` to method

**Comment by micheleriva** [comment]
Hi @eLeontev you're right! I fixed it by adding `this` to the method call, what a stupid error ☹️
