### ISSUE TITLE
Remember position on image drag

### ISSUE THREAD

**Issue by micheleriva** [micheleriva/vue-product-spinner#5]
**Describe the bug**
When you drag the image, it will rotate until your mouse is pressed down.
If you release it and then start to drag the image again, it will "forget" the last frame.

**To Reproduce**
1. Go to https://micheleriva.github.io/vue-product-spinner/
2. Drag the image from left to right or right to left
3. Release the mouse
4. Start to drag again from a new mouse position

**Comment by draconteus** [comment]
I'd work on this.

**Comment by micheleriva** [comment]
Thank you sooooo much!
Any PR is really appreciated, feel free then to add yourself to the contributor list in the package.json 😊

**Comment by bedis-elacheche** [comment]
Hi @micheleriva. I'm unable to reproduce the bug using https://micheleriva.github.io/vue-product-spinner. When I start drag the image, it dissapears. I had the same behavior on both firefox and chrome

**Comment by micheleriva** [comment]
Hi @bedis-elacheche ,
I'm working on a rewrite of the library so it won't show this error again!
